# Generated by Django 4.1.3 on 2022-12-05 15:26

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(error_messages={'unique': 'A user with that phone already exists.'}, help_text='Required. 11 character. digits only.', max_length=11, unique=True, validators=[core.validators.PhoneValidator()], verbose_name='phone number'),
        ),
    ]
