# Generated by Django 4.1.3 on 2022-12-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_address_options_alter_otpcode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='image',
            field=models.ImageField(blank=True, default='E:/boot camp/project/Maktab_78_Sajjad_Kashi/shop/accounts/static/image/agents/1.jpg', null=True, upload_to='profile/', verbose_name='image'),
        ),
    ]
