# Generated by Django 4.1.3 on 2022-12-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_alter_profileuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'User'), (1, 'Customer'), (2, 'Product Manager'), (3, 'supervisor'), (4, 'Operator')], default=0, max_length=20, verbose_name='role'),
        ),
    ]
