# Generated by Django 4.1.3 on 2022-12-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profileuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
