# Generated by Django 4.1.3 on 2023-01-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='adderess',
            new_name='address',
        ),
    ]
