# Generated by Django 4.1.3 on 2022-12-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profileuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='number_try',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
