# Generated by Django 4.1.3 on 2022-12-06 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_otpcode_number_try'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='create_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='update_time',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='otpcode',
            old_name='create_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='otpcode',
            old_name='update_time',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='profileuser',
            old_name='create_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='profileuser',
            old_name='update_time',
            new_name='updated_at',
        ),
    ]
