# Generated by Django 4.1.3 on 2022-12-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10)),
                ('min_purchase', models.DecimalField(decimal_places=2, max_digits=20)),
                ('max_discount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('percent', models.PositiveSmallIntegerField()),
                ('expire_time', models.DateTimeField()),
                ('limit_number', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('event', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(choices=[(1, 'Percent'), (2, 'Amount')])),
                ('percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('start_time', models.DateTimeField()),
                ('expire_time', models.DateTimeField()),
                ('event', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
