# Generated by Django 4.1.3 on 2022-12-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Coupon', 'verbose_name_plural': 'Coupons'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Discount', 'verbose_name_plural': 'Discounts'},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=10, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='event',
            field=models.CharField(max_length=100, verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expire_time',
            field=models.DateTimeField(verbose_name='expire time'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='limit_number',
            field=models.IntegerField(verbose_name='limit number'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_discount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='max discount'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_purchase',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='min purchase'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='percent',
            field=models.PositiveSmallIntegerField(verbose_name='percent'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_time',
            field=models.DateTimeField(verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='event',
            field=models.CharField(max_length=100, verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='expire_time',
            field=models.DateTimeField(verbose_name='expire time'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='percent'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start_time',
            field=models.DateTimeField(verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.IntegerField(choices=[(1, 'Percent'), (2, 'Amount')], verbose_name='type'),
        ),
    ]
