# Generated by Django 4.1.3 on 2022-12-06 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('meta_title', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_shop', models.BooleanField(default=False)),
                ('warehouse_code', models.CharField(max_length=50)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('quantity', models.PositiveIntegerField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('is_delete', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='category',
            old_name='create_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='update_time',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='create_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='update_time',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='create_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='update_time',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='create_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='update_time',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='create_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='name',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='update_time',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='item',
        ),
        migrations.RemoveField(
            model_name='price',
            name='item',
        ),
        migrations.RemoveField(
            model_name='property',
            name='item',
        ),
        migrations.AddField(
            model_name='category',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='product', to='product.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='product',
            field=models.ForeignKey(default=24.679012345679013, on_delete=django.db.models.deletion.ProtectedError, related_name='galery', to='product.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(default=24.679012345679013, on_delete=django.db.models.deletion.ProtectedError, related_name='prices', to='product.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='product',
            field=models.ForeignKey(default=24.679012345679013, on_delete=django.db.models.deletion.ProtectedError, related_name='property', to='product.product'),
            preserve_default=False,
        ),
    ]
