# Generated by Django 4.1.3 on 2022-12-09 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discount', '0002_alter_coupon_options_alter_discount_options_and_more'),
        ('product', '0002_remove_product_categories_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gallery', 'verbose_name_plural': 'Galleries'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'price', 'verbose_name_plural': 'prices'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Products', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterField(
            model_name='category',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_navbar',
            field=models.BooleanField(verbose_name='is_navbar'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childrens', to='product.category', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='main_pic',
            field=models.ImageField(upload_to='category/', verbose_name='main pic'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='galery', to='product.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='image',
            name='galery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.gallery', verbose_name='galery'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='image/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_alt',
            field=models.CharField(max_length=50, verbose_name='image alt'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='price',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='product.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='product.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discount.discount', verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ends at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='is delete'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_shop',
            field=models.BooleanField(default=False, verbose_name='is shop'),
        ),
        migrations.AlterField(
            model_name='product',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='published at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='starts at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warehouse_code',
            field=models.CharField(max_length=50, verbose_name='warehouse code'),
        ),
        migrations.AlterField(
            model_name='property',
            name='key',
            field=models.CharField(max_length=50, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='property',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property', to='product.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='property',
            name='value',
            field=models.CharField(max_length=50, verbose_name='value'),
        ),
    ]
