# Generated by Django 4.1.3 on 2022-12-07 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
        ('product', '0003_alter_product_is_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount',
            new_name='discount_amount',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discount.discount'),
        ),
    ]
