# Generated by Django 4.1.3 on 2022-12-12 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_gallery_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='galery',
        ),
        migrations.AddField(
            model_name='image',
            name='gallery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.gallery', verbose_name='gallery'),
            preserve_default=False,
        ),
    ]
