# Generated by Django 4.1.3 on 2022-12-13 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_image_galery_image_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ('-created_at',), 'verbose_name': 'price', 'verbose_name_plural': 'prices'},
        ),
        migrations.RemoveField(
            model_name='image',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='gallery',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='product.image', verbose_name='gallery'),
        ),
        migrations.AddField(
            model_name='image',
            name='image1',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='image1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='image2',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='image2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='image3',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='image3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.category', verbose_name='category'),
        ),
    ]
