# Generated by Django 4.1.3 on 2022-12-13 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_gallery_images_image_gallery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image3',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.gallery', verbose_name='gallery'),
        ),
    ]
