# Generated by Django 4.1.3 on 2022-12-16 18:04

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_image_image1_remove_image_image2_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('soft_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
