# Generated by Django 4.1.3 on 2022-12-19 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_managers_alter_product_deleted_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
    ]
