# Generated by Django 4.1.3 on 2022-12-09 21:08

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discount', '0002_alter_coupon_options_alter_discount_options_and_more'),
        ('product', '0003_alter_category_options_alter_gallery_options_and_more'),
        ('order', '0003_alter_order_receiver_mobile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=100, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=100, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='order',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(default='iran', max_length=100, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='discount.coupon', verbose_name='coupon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='grand',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='grand'),
        ),
        migrations.AlterField(
            model_name='order',
            name='province',
            field=models.CharField(max_length=100, verbose_name='province'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiver_mobile',
            field=models.CharField(max_length=15, validators=[core.validators.PhoneValidator()], verbose_name='receiver mobile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiver_name',
            field=models.CharField(max_length=100, verbose_name='receiver name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='shipping'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='sub total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='tax'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='warehouse_code',
            field=models.CharField(max_length=50, verbose_name='warehouse code'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='code',
            field=models.CharField(max_length=50, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='order.order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Cancelled'), (3, 'Failed'), (4, 'Pending'), (5, 'Declined'), (6, 'Rejected'), (7, 'Success')], default=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
