# Generated by Django 4.1.3 on 2023-01-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default=0, max_length=20, verbose_name='postal code'),
            preserve_default=False,
        ),
    ]
