# Generated by Django 4.1.3 on 2023-01-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='discount',
        ),
    ]
